// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
//import "dotenv/config";
//import { defineConfig } from "prisma/config";

//export default defineConfig({
//  schema: "./prisma/schema.prisma",
//  migrations: {
//    path: "prisma/migrations",
//    seed: 'tsx prisma/seed.ts',
//  },
//  datasource: {
//    url: process.env["DATABASE_URL"],
//  },
//});

import { defineConfig } from 'prisma/config'
import { config } from 'dotenv'
import path from 'path'

// process.cwd() always points to project root on Windows
const root = process.cwd()

// Load .env first, then .env.local overrides
config({ path: path.join(root, '.env') })
config({ path: path.join(root, '.env.local'), override: true })

// Debug — confirm it loaded (remove this line after confirming)
console.log('DATABASE_URL loaded:', !!process.env.DATABASE_URL)

export default defineConfig({
  schema: path.join(root, 'prisma/schema.prisma'),
  datasource: {
    url: process.env.DATABASE_URL!,
  },
  migrations: {
    seed: 'node --env-file=.env --import tsx/esm prisma/seed.ts'
  },
})